extends:
    - "stylelint-config-standard"
    - "stylelint-config-prettier"
rules:
    "at-rule-no-unknown":
        - true
        - "ignoreAtRules":
            - "function"
            - "if"
            - "else"
            - "each"
            - "extend"
            - "include"
            - "mixin"
            - "return"
            - "warn"